# Generated by Django 4.1.7 on 2023-02-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientForRecipe',
            new_name='IngredientRecipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='autor',
            new_name='author',
        ),
    ]
