# Generated by Django 4.1.7 on 2023-02-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ingredientforrecipe_ingredientrecipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='weight',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='title',
            new_name='name',
        ),
    ]
